"""Dropped unique constraint from permissions table

Revision ID: f95cde8d90bc
Revises: 528cd10edcce
Create Date: 2019-11-22 18:34:40.725533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95cde8d90bc'
down_revision = '528cd10edcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint('permission_operation_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_unique_constraint('permission_operation_key', ['operation'])

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
